import React, { useState, useRef } from 'react'
import { useEffect } from 'react';
import { Card, FormField, Loader } from '../components';
import { config } from '../config';

function Home() {
  const { HOST, API } = config;
  const host = HOST.development;
  
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState({
    searchResults: [],
    photos: []
  });

  const searchText = useRef('');
  let controller = null;

  const fetchPosts = async () => {
    setLoading(true);
    const api = API.photo;

    try {
      controller = new AbortController();
      const signal = controller.signal;
      const response = await fetch(host.concat(api), {
        method: 'GET',
        headers: {
          'Content-Type': 'appplication/json',
        },
        signal: signal
      });

      const result = await response.json();
      setData({...data, photos: result.data.reverse()});

    } catch (error) {
      alert(error);
    } finally{
      setLoading(false);
    }

  };

  // useEffect(() => {
  //   fetchPosts();
  //   return () => {
  //     if(controller){
  //       controller.abort();
  //     }
  //   }
  // }, []);

  const handleSearchText = (e) => {
    const { value } = e.target;
    
    searchText.current = value;
    setTimeout(() => {
      const searchResult = data.photos.filter(
        (photo) => [photo.name, photo.prompt].filter((item) => item.toLowerCase().includes(value.toLowerCase())).length > 0
      );
      setData({ ...data, searchResults: searchResult });
    }, 500);
  };

  return (
    <div>
      <div className='mt-2'>
        <h2 className='text-[30px] text-[#242428] font-bold'>The Community Showcase</h2>
        <p className='mt-2 text-[#777a7e] text-sm'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>
      <div className='mt-5'>
        <FormField
          labelName="Search post"
          name="text"
          type="text"
          placeholder="Enter something to search.."
          value={searchText.current}
          handleChange={handleSearchText}
        />
      </div>
      <div className='mt-10'>
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            { searchText.current &&
              (<h3 className='font-medium text-[#9a9da0] text-xl mb-2'>
                List results relevant to your search <span className='text-[#232329]'>{searchText.current}</span>
              </h3>
              )
            }

            <div className='grid xl:grid-cols-4 lg:grid-cols-3 sm:grid-cols-2 xs:grid-cols-1 gap-3'>
              <Card searchText={searchText} data={data} />
            </div>
          </>
        )}
      </div>
    </div>

  )
}

export default Home